  function generateProductsJS() {
                const productsData = builderState.products.map(p => ({
                    id: p.id,
                    name: p.name,
                    category: p.category || 'Uncategorized',
                    price: Number(p.price) || 0,
                    salePrice: p.salePrice ? Number(p.salePrice) : null,
                    description: p.description || '',
                    rating: Number(p.rating) || 0,
                    stock: Number(p.stock) || 0,
                    sku: p.sku || '',
                    image: p.imageBlobId ? `[BLOB:${p.imageBlobId}]` : '',
                }));
                const jsonData = JSON.stringify(productsData, null, 2);
                return `// AyeshaMall Products Database
        // Auto-generated by BuildSite.html
        // Generated: ${new Date().toISOString()}
        const products = ${jsonData};

        // Product lookup helper
        function getProductById(id) {
          return products.find(p => p.id === id);
        }

        // Get products by category
        function getProductsByCategory(category) {
          return products.filter(p => p.category === category);
        }

        // Get all unique categories
        function getAllCategories() {
          return [...new Set(products.map(p => p.category).filter(Boolean))];
        }

        // Export for module usage
        if (typeof module !== 'undefined' && module.exports) {
          module.exports = { products, getProductById, getProductsByCategory, getAllCategories };
        }
        `;
            }

          function generateIndexHTML() {
    const siteName = escapeHTML(builderState.siteName);
    const siteTitle = escapeHTML(builderState.siteTitle || builderState.siteName);
    const seoTitle = escapeHTML(builderState.seoTitle || siteTitle);
    const metaDesc = escapeHTML(builderState.metaDescription || '');
    const keywords = escapeHTML(builderState.keywords || '');
    const author = escapeHTML(builderState.author || '');
    const primaryColor = builderState.primaryColor || '#6c5ce7';
    const secondaryColor = builderState.secondaryColor || '#00c897';
    const fontFamily = builderState.fontFamily || "'Segoe UI', system-ui, sans-serif";

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${seoTitle}</title>
  <meta name="description" content="${metaDesc}">
  <meta name="keywords" content="${keywords}">
  <meta name="author" content="${author}">
  <meta name="theme-color" content="${primaryColor}">
  <meta property="og:title" content="${seoTitle}">
  <meta property="og:description" content="${metaDesc}">
  <meta property="og:type" content="website">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="stylesheet" href="style.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body>
  <header class="site-header">
    <div class="container">
      <a href="/" class="logo">
        <img src="images/logo.png" alt="${siteName} Logo" class="logo-img" onerror="this.style.display='none'">
        <span class="logo-text">${siteName}</span>
      </a>
      <nav class="site-nav" aria-label="Main navigation">
        <ul>
          <li><a href="#home">Home</a></li>
          <li><a href="#products">Products</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
      <button class="mobile-menu-toggle" aria-label="Toggle menu">☰</button>
    </div>
  </header>

  <main>
    <section class="hero" id="home">
      <div class="hero-overlay"></div>
      <img src="images/hero.webp" alt="Hero Banner" class="hero-bg" onerror="this.style.display='none'">
      <div class="hero-content container">
        <h1>Welcome to ${siteName}</h1>
        <p class="hero-subtitle">Discover premium products curated just for you</p>
        <a href="#products" class="btn btn-primary">Shop Now</a>
      </div>
    </section>

    <section class="banner-section" id="about">
      <div class="container">
        <img src="images/banner.webp" alt="Promotional Banner" class="banner-img" onerror="this.style.display='none'">
        <div class="banner-text">
          <h2>Why Choose ${siteName}?</h2>
          <p>We offer handpicked quality products with exceptional customer service and fast, reliable shipping.</p>
        </div>
      </div>
    </section>

    <section class="products-section" id="products">
      <div class="container">
        <h2 class="section-title">Our Products</h2>
        <div class="products-grid" id="productsGrid">
          <!-- Products rendered by script.js -->
        </div>
      </div>
    </section>

    <section class="contact-section" id="contact">
      <div class="container">
        <h2>Get In Touch</h2>
        <p>Email: ${escapeHTML(builderState.email || '')}</p>
        <p>Phone: ${escapeHTML(builderState.phone || '')}</p>
      </div>
    </section>
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>&copy; ${new Date().getFullYear()} ${siteName}. All rights reserved.</p>
      <p>Built with ❤️ by ${author}</p>
    </div>
  </footer>

  <script src="products.js"></script>
  <script src="script.js"></script>
</body>
</html>`;
}

         function generateStyleCSS() {
    const primary = builderState.primaryColor || '#6c5ce7';
    const secondary = builderState.secondaryColor || '#00c897';
    const bg = builderState.bgColor || '#ffffff';
    const text = builderState.textColor || '#1a1a2e';
    const font = builderState.fontFamily || "'Segoe UI', system-ui, sans-serif";

    return `/* AyeshaMall Styles — Auto-generated by BuildSite.html */
:root {
  --primary: ${primary};
  --primary-light: ${lightenColor(primary, 20)};
  --primary-dark: ${darkenColor(primary, 20)};
  --secondary: ${secondary};
  --bg: ${bg};
  --text: ${text};
  --text-light: ${lightenColor(text, 40)};
  --font: ${font};
  --radius: 8px;
  --shadow: 0 2px 16px rgba(0,0,0,0.08);
  --max-width: 1200px;
}

*, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }

html { scroll-behavior: smooth; font-size: 16px; }

body {
  font-family: var(--font);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

.container {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: 0 1.5rem;
}

/* Header */
.site-header {
  background: #fff;
  border-bottom: 1px solid #eee;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: var(--shadow);
}
.site-header .container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-top: 0.75rem;
  padding-bottom: 0.75rem;
}
.logo {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  text-decoration: none;
  color: var(--text);
  font-weight: 700;
  font-size: 1.25rem;
}
.logo-img { height: 36px; width: auto; }
.site-nav ul { display: flex; list-style: none; gap: 1.5rem; }
.site-nav a {
  text-decoration: none;
  color: var(--text);
  font-weight: 500;
  transition: color 0.2s;
}
.site-nav a:hover { color: var(--primary); }
.mobile-menu-toggle { display: none; background: none; border: none; font-size: 1.5rem; cursor: pointer; }

/* Hero */
.hero {
  position: relative;
  min-height: 420px;
  display: flex;
  align-items: center;
  overflow: hidden;
  background: var(--primary-dark);
}
.hero-bg {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
  opacity: 0.4;
}
.hero-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(0,0,0,0.6), rgba(0,0,0,0.3));
}
.hero-content {
  position: relative;
  z-index: 2;
  color: #fff;
  text-align: center;
  padding: 4rem 1.5rem;
}
.hero-content h1 { font-size: 2.8rem; font-weight: 800; margin-bottom: 0.5rem; }
.hero-subtitle { font-size: 1.2rem; opacity: 0.9; margin-bottom: 1.5rem; }

/* Buttons */
.btn {
  display: inline-block;
  padding: 0.7rem 1.6rem;
  border-radius: var(--radius);
  font-weight: 600;
  text-decoration: none;
  cursor: pointer;
  border: none;
  transition: all 0.2s;
  font-size: 0.95rem;
}
.btn-primary { background: var(--primary); color: #fff; }
.btn-primary:hover { background: var(--primary-dark); transform: translateY(-1px); box-shadow: 0 4px 12px rgba(0,0,0,0.2); }

/* Banner */
.banner-section { padding: 3rem 0; }
.banner-section .container { display: flex; align-items: center; gap: 2rem; flex-wrap: wrap; }
.banner-img { max-width: 400px; width: 100%; border-radius: var(--radius); }
.banner-text h2 { font-size: 1.8rem; margin-bottom: 0.5rem; }

/* Products */
.products-section { padding: 3rem 0; background: #f9fafb; }
.section-title { text-align: center; font-size: 2rem; margin-bottom: 2rem; }
.products-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 1.5rem;
}
.product-card {
  background: #fff;
  border-radius: var(--radius);
  overflow: hidden;
  box-shadow: var(--shadow);
  transition: transform 0.2s, box-shadow 0.2s;
}
.product-card:hover { transform: translateY(-4px); box-shadow: 0 8px 24px rgba(0,0,0,0.12); }
.product-card-img { width: 100%; height: 200px; object-fit: cover; background: #eee; }
.product-card-body { padding: 1rem; }
.product-card-name { font-weight: 700; font-size: 1rem; }
.product-card-category { font-size: 0.75rem; color: var(--primary); text-transform: uppercase; letter-spacing: 0.05em; }
.product-card-price { font-weight: 700; color: var(--secondary); font-size: 1.1rem; }
.product-card-sale { text-decoration: line-through; color: #999; font-size: 0.85rem; margin-left: 0.4rem; }
.product-card-rating { color: #f39c12; font-size: 0.85rem; }
.product-card-stock { font-size: 0.75rem; color: #666; }

/* Contact */
.contact-section { padding: 3rem 0; text-align: center; }
.contact-section h2 { margin-bottom: 1rem; }

/* Footer */
.site-footer { background: #1a1a2e; color: #ccc; text-align: center; padding: 1.5rem 0; font-size: 0.85rem; }
.site-footer p { margin: 0.25rem 0; }

/* Responsive */
@media (max-width: 768px) {
  .site-nav { display: none; }
  .mobile-menu-toggle { display: block; }
  .hero-content h1 { font-size: 2rem; }
  .banner-section .container { flex-direction: column; text-align: center; }
  .products-grid { grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); }
}
@media (max-width: 480px) {
  .products-grid { grid-template-columns: 1fr; }
  .hero { min-height: 300px; }
  .hero-content h1 { font-size: 1.6rem; }
}`;
}

  // ─── BUILDER STATE ────────────────────
            const builderState = {
                siteName: 'AyeshaMall Store',
                siteTitle: 'AyeshaMall — Premium Products',
                companyName: 'AyeshaMall Ltd.',
                author: 'AyeshaMall Team',
                email: 'contact@ayeshamall.com',
                phone: '+1 (555) 123-4567',
                seoTitle: 'AyeshaMall — Premium Quality Products Online',
                metaDescription: 'Discover premium quality products at AyeshaMall. Shop the latest trends with fast shipping and exceptional customer service.',
                keywords: 'ayeshamall, online store, premium products, shopping, ecommerce',
                primaryColor: '#6c5ce7',
                secondaryColor: '#00c897',
                bgColor: '#ffffff',
                textColor: '#1a1a2e',
                fontFamily: "'Segoe UI', system-ui, sans-serif",
                products: [], // { id, imageBlobId, name, category, price, salePrice, description, rating, stock, sku }
                imageRefs: {
                    logo: null,
                    favicon: null,
                    hero: null,
                    banner: null,
                }, // blobId per image type
            };
function generateScriptJS() {
    return `// AyeshaMall Scripts — Auto-generated by BuildSite.html
(function() {
  'use strict';

  // Render products from products.js data
  function renderProducts() {
    const grid = document.getElementById('productsGrid');
    if (!grid || typeof products === 'undefined') return;

    grid.innerHTML = '';
    products.forEach(product => {
      const card = document.createElement('div');
      card.className = 'product-card';
      const imageSrc = product.image && product.image.startsWith('[BLOB:')
        ? product.image
        : (product.image || 'images/products/placeholder.webp');

      const onErrorImg = 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22300%22 height=%22200%22><rect fill=%22%23ddd%22 width=%22300%22 height=%22200%22/><text fill=%22%23999%22 x=%22150%22 y=%22100%22 text-anchor=%22middle%22 dy=%22.3em%22 font-size=%2216%22>No Image</text></svg>';
      
      card.innerHTML = '<img src="' + escapeAttr(imageSrc) + '" alt="' + escapeAttr(product.name) + '" class="product-card-img" loading="lazy" onerror="this.src=\\'' + onErrorImg + '\\'">' +
        '<div class="product-card-body">' +
        '<span class="product-card-category">' + escapeHTML(product.category || '') + '</span>' +
        '<h3 class="product-card-name">' + escapeHTML(product.name) + '</h3>' +
        '<p class="product-card-description" style="font-size:0.8rem;color:#666;">' + escapeHTML((product.description || '').substring(0, 80)) + (product.description && product.description.length > 80 ? '...' : '') + '</p>' +
        '<div>' +
        '<span class="product-card-price">$' + Number(product.price).toFixed(2) + '</span>' +
        (product.salePrice ? '<span class="product-card-sale">$' + Number(product.salePrice).toFixed(2) + '</span>' : '') +
        '</div>' +
        '<span class="product-card-rating">' + '★'.repeat(Math.round(product.rating || 0)) + '☆'.repeat(5 - Math.round(product.rating || 0)) + ' (' + (product.rating || 0) + ')</span>' +
        '<span class="product-card-stock">' + (product.stock > 0 ? 'In Stock: ' + product.stock : 'Out of Stock') + '</span>' +
        '</div>';
      
      grid.appendChild(card);
    });
  }

  // Mobile menu toggle
  document.querySelector('.mobile-menu-toggle')?.addEventListener('click', function() {
    const nav = document.querySelector('.site-nav');
    if (nav) nav.style.display = nav.style.display === 'block' ? 'none' : 'block';
  });

  // Initialize
  document.addEventListener('DOMContentLoaded', function() {
    renderProducts();
    console.log('AyeshaMall website initialized with ' + (typeof products !== 'undefined' ? products.length : 0) + ' products.');
  });

 
        function escapeHTML(str) {
    if (str === null || str === undefined) return '';

    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function escapeAttr(str) {
    return escapeHTML(str);
}
        })();`;
            }


            function escapeHTML(str) {
    if (str === null || str === undefined) return '';

    return String(str)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function escapeAttr(str) {
    return escapeHTML(str);
}

            function generateRobotsTxt() {
                return `User-agent: *
        Allow: /
        Sitemap: sitemap.xml

        # Disallow admin areas
        Disallow: /admin/
        Disallow: /api/

        # Crawl delay
        Crawl-delay: 1
        `;
            }

            function generateSitemapXML() {
                const baseUrl = `https://${builderState.siteName.toLowerCase().replace(/[^a-z0-9]/g, '')}.com`;
                const now = new Date().toISOString().split('T')[0];
                return `<?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
            <loc>${baseUrl}/</loc>
            <lastmod>${now}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
          </url>
          <url>
            <loc>${baseUrl}/#products</loc>
            <lastmod>${now}</lastmod>
            <changefreq>weekly</changefreq>
            <priority>0.8</priority>
          </url>
          <url>
            <loc>${baseUrl}/#about</loc>
            <lastmod>${now}</lastmod>
            <changefreq>monthly</changefreq>
            <priority>0.6</priority>
          </url>
          <url>
            <loc>${baseUrl}/#contact</loc>
            <lastmod>${now}</lastmod>
            <changefreq>monthly</changefreq>
            <priority>0.5</priority>
          </url>
        </urlset>`;
            }

            function generateManifestJSON() {
                const siteName = builderState.siteName;
                const primaryColor = builderState.primaryColor || '#6c5ce7';
                return JSON.stringify({
                    name: siteName,
                    short_name: siteName.substring(0, 12),
                    description: builderState.metaDescription || '',
                    start_url: '/',
                    display: 'standalone',
                    background_color: builderState.bgColor || '#ffffff',
                    theme_color: primaryColor,
                    orientation: 'any',
                    icons: [{
                        src: 'images/favicon.ico',
                        sizes: '64x64 32x32 24x24 16x16',
                        type: 'image/x-icon',
                    }, {
                        src: 'images/logo.png',
                        sizes: '192x192',
                        type: 'image/png',
                    }, {
                        src: 'images/logo.png',
                        sizes: '512x512',
                        type: 'image/png',
                    }],
                }, null, 2);
            }

            // ─── COLOR UTILITIES ──────────────────
            function lightenColor(hex, percent) {
                const num = parseInt(hex.replace('#', ''), 16);
                const amt = Math.round(2.55 * percent);
                const R = Math.min(255, (num >> 16) + amt);
                const G = Math.min(255, ((num >> 8) & 0x00FF) + amt);
                const B = Math.min(255, (num & 0x0000FF) + amt);
                return `#${(1 << 24 | R << 16 | G << 8 | B).toString(16).slice(1)}`;
            }

            function darkenColor(hex, percent) {
                const num = parseInt(hex.replace('#', ''), 16);
                const amt = Math.round(2.55 * percent);
                const R = Math.max(0, (num >> 16) - amt);
                const G = Math.max(0, ((num >> 8) & 0x00FF) - amt);
                const B = Math.max(0, (num & 0x0000FF) - amt);
                return `#${(1 << 24 | R << 16 | G << 8 | B).toString(16).slice(1)}`;
            }
